# config/enums/message.yml
expiration_type:
  - name: hour
    label: "Hour"
    id: 0
  - name: hours
    label: "Hours"
    id: 1
  - name: day
    label: "Day"
    id: 2
  - name: days
    label: "Days"
    id: 3
  - name: week
    label: "Week"
    id: 4
  - name: weeks
    label: "Weeks"
    id: 5
  - name: month
    label: "Month"
    id: 6
  - name: months
    label: "Months"
    id: 7
  - name: view
    label: "View"
    id: 8
  - name: views
    label: "Views"
    id: 9
